---
stages:
- tests
- release_publish

Unit Test:
  dependencies: []
  image: gitlab.krone.at:5000/krn/backend:beta
  tags:
    - docker
  services:
    - mysql:latest
  stage: tests
  variables:
    # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
    MYSQL_ROOT_PASSWORD: somepw
  script:
    - composer update
    - apt-get update && apt-get install -y subversion #FIXME should be in DOCKER_BASE
    - pecl install xdebug && echo "extension=xdebug.so" > /usr/local/etc/php/conf.d/xdebug.ini
    - bin/install-wp-tests.sh wordpress_test root 'somepw' mysql latest
    - composer update
    - phpunit --colors=always --coverage-text=1.txt
    - grep "Lines:" 1.txt
  except:
      - /^v.*/ # do not unit test release tags
      - after_build
      - after_build_beta


release:publish:
  dependencies: []
  image: gitlab.krone.at:5000/krn/fastlane_runner:latest
  stage: release_publish
  script:
  - fastlane publish_release
  tags:
  - docker
  only:
  - release
  - fastlane
  - beta
  - master
before_script:
- eval $(ssh-agent -s)
- ssh-add <(echo "$SSH_DEPLOY_KEY")
