- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v2.2.0
  hooks:
      - id: commitlint
        stages: [commit-msg]
        language_version: "12.21.0"
        additional_dependencies: ['commitlint-config-gitmoji', 'commitlint', "@commitlint/types"]


- repo: https://github.com/digitalpulp/pre-commit-php.git
  rev: 1.4.0
  hooks:
  - id: php-cs-fixer
    files: \.(php)$
    args: [""]
