language: php
sudo: false
dist: trusty

php:
  - 7.1
  - 7.2

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer global require hirak/prestissimo
  - bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 latest

install: 
  - travis_retry travis_wait composer install --no-interaction 

script:
  -  vendor/phpunit/phpunit/phpunit -v

before_deploy:
  - rm -vfr .git
  - composer --no-dev --verbose --optimize-autoloader --prefer-dist install
deploy:
  - provider: wordpress-plugin
    edge:
      source: TypistTech/dpl
      branch: add-wordpress-plugin-deployment
    on:
      php: 7.2
      tags: true
      repo: KroneMultimedia/plugin-timeshift
    slug:  $WORDPRESS_PLUGIN_SLUG
    username: $WORDPRESS_ORG_USERNAME
    password: $WORDPRESS_ORG_PASSWORD
    build_dir: .


jobs:
  include:

    - stage: Code Style
      script: 
        - composer cs-check
      env: CS-FIXER=true

    - stage: coverage
      script: 
        - phpdbg -qrr vendor/bin/phpunit --coverage-clover clover.xml
      after_success:
        - vendor/bin/ocular code-coverage:upload --format=php-clover clover.xml --revision=$TRAVIS_COMMIT
